sudo: false

language: node_js

node_js:
    - "7"

before_install:
    - export PORT=5000

services:
    - mongodb

install:
    - npm install

before_script:
    - npm install -g mocha
    - npm install -g istanbul
    - npm install -g gulp
    - npm install -g debug

script:
    - gulp test
