version: "1.0"
stages:
  - "clone"
  - "unit"
  - "build"
  - "integration"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "codefreshdemo/demochat"
    revision: "master"
    stage: "clone"

  build_dev_image:
    title: "Building Dev image"
    type: "build"
    image_name: "codefreshdemo/demochat"
    working_directory: "${{clone}}"
    tag: "dev"
    dockerfile: "Dockerfile.dev"
    stage: "unit"

  test:
    title: "Running test"
    type: "freestyle" 
    image: ${{build_dev_image}} 
    working_directory: /root/demochat
    commands:
      - 'npm run test'
    stage: "unit"
  
  build_image:
    title: "Building App image"
    type: "build"
    image_name: "codefreshdemo/demochat"
    working_directory: "${{clone}}"
    tag: "dev"
    dockerfile: "Dockerfile"
    stage: "build"
    
  integration_step:
    type: composition
    stage: 'integration'
    composition:
      version: '2'
      services:
        app:
          image: ${{build_image}}
          links:
            - mongo
          ports:
            - 5000
        mongo:
          image: mongo
    composition-candidates:
      main:
        image: nhoag/curl
        command: bash -c "sleep 30 && curl http://app:5000/" | echo 'works'    

