version: '3'
services:
  app:
    image: demochat:latest
    links:
      - mongo
    ports:
      - 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 5s
      timeout: 5s
      retries: 3
  mongo:
    image: mongo
#  main:
#    image: nhoag/curl
#    depends_on:
#      - app
#    command: bash -c "sleep 30 && curl http://app:5000/" | echo 'works'
